## istructions to build the image ##
# export INSTALL_XDEBUG=true
# docker compose build

services:
    web:
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
        args:
            INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    #        http_proxy: ${http_proxy:-false}
    #        https_proxy: ${https_proxy:-false}
      container_name: enkel_klient_webserver
      volumes:
        - ./:/var/www/html/
        - ./logs:/var/log/apache2/
      networks:
        - internal
      ports:
      - "8210:80"
      environment:
        - no_proxy=portico_api,portico_api:8088,fdvapp01e.srv.bergenkom.no,fdvapp01e.srv.bergenkom.no:8210
        - NO_PROXY=portico_api,portico_api:8088,fdvapp01e.srv.bergenkom.no,fdvapp01e.srv.bergenkom.no:8210

networks:
    internal:
        name: portico_internal
        external: true
