version: '3.9'

services:
    web:
      restart: always
      build : .
      container_name: lrs
 #     image: sigurdne/portico_estate_webserver:latest
      volumes:
      - ./src:/var/www/html/enkel_klient/
      networks:
      - frontend
      ports:
      - "8210:80"
      labels:
      - "traefik.enable=false"

networks:
    frontend:
       external:
           name: outside
