## istructions to build the image ##
# export INSTALL_XDEBUG=true
# docker compose build

services:
    web:
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
        args:
            INSTALL_XDEBUG: ${INSTALL_XDEBUG}
            http_proxy: ${http_proxy:-false}
            https_proxy: ${https_proxy:-false}
      container_name: lrs
 #     image: sigurdne/portico_estate_webserver:latest
      volumes:
      - ./src:/var/www/html/enkel_klient/
      networks:
        - internal
      ports:
      - "8210:80"


networks:
    internal:
        driver: bridge
