cutoff_size = 40
site_title = "Innmeldingsskjema"
keywords = "Helpdesk,Aktiv kommune"
form_header = "Skjema for innmelding av saker til etat for boligforvaltning"
cache_refresh_token = 54

[site]
title = "EBF-BoligReg"
keywords = "Portico, Etat for boligforvaltning, Bergen kommune, boligforvaltning"
description = "EBF-BoligReg er et digitalt skjema for innmelding og oppfølging av saker til etat for boligforvaltning i Bergen kommune."
author = "Bergen kommune, etat for boligforvaltning. Basert på PorticoEstate"


[footer]
contact_info_name = "Etat for boligforvaltning, Bergen kommune"
contact_info_mail_address = "Postboks 7700, 5020 Bergen"
contact_info_visiting_address = "Peter Motzfeldts gate 1A"
contact_info_opening_hours = "Mandag - fredag 11:00 - 14:00"
contact_info_phone = "55 56 60 00"
contact_info_org_nr = "982 715 539"
cookie_policy = "https://www.bergen.kommune.no/innbyggerhjelpen/demokrati-og-innbyggerrettigheter/innbyggerrettigheter/personvern/bruk-av-informasjonskapsler-pa-kommunens-nettside"
privacy_policy = "https://www.bergen.kommune.no/innbyggerhjelpen/demokrati-og-innbyggerrettigheter/innbyggerrettigheter/personvern/personvernerklaring-for-bergen-kommune"
#accessibility_statement = "https://uustatus.no/nb/erklaringer/publisert/bbfd8bda-4ec2-48e5-af0b-3bbcfef99ce7"

[setup]
bold = true

[landing]
title = "Velkommen til Bergen kommune, etat for boligforvaltning"
subtitle = "Digitale skjema"
description = "Velg ønsket skjema fra menyen til venstre for å komme i gang."

[services]
helpdesk = "Feil og mangler"
nokkelbestilling = "Nøkkelbestilling"
inspection_1 = "Brannforebygging"
invoicerequest = "Fakturaforespørsel"

[inspection_1]
enable_fileupload = true
; WCAG 3.3.4 Error Prevention configuration
form_summary_on_submit = true
confirmation_dialog_enabled = true
auto_save_enabled = true
change_tracking_enabled = true

[helpdesk]
enable_fileupload = true
cat_id = 10006
; WCAG 3.3.4 Error Prevention configuration
form_summary_on_submit = true
confirmation_dialog_enabled = false
auto_save_enabled = true
change_tracking_enabled = false

[nokkelbestilling]
enable_fileupload = true
cat_id = 10106
; WCAG 3.3.4 Error Prevention configuration
form_summary_on_submit = true
confirmation_dialog_enabled = true
auto_save_enabled = true
change_tracking_enabled = true

[invoicerequest]
enable_fileupload = true
cat_id = 10239
; WCAG 3.3.4 Error Prevention configuration
form_summary_on_submit = true
confirmation_dialog_enabled = false
auto_save_enabled = true
change_tracking_enabled = true